
modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="kellomod"
version="${file.jarVersion}"
displayName="Kello's Great Filter"
logoFile="logo.png"
credits="The Great Filter"
authors="Kello"
description='''
Have some Kelloggs Frosted Flakes.

The Great Filter, in the context of the Fermi paradox, is one possible resolution of the paradox. It posits that in the development of life from the earliest stages of abiogenesis to reaching the highest levels of development on the Kardashev scale, there exists some particular barrier to development that makes detectable extraterrestrial life exceedingly rare. The concept originates in Robin Hanson's argument that the failure to find any extraterrestrial civilizations in the observable universe implies that something is wrong with one or more of the arguments (from various scientific disciplines) that the appearance of advanced intelligent life is probable; this observation is conceptualized in terms of a "Great Filter" which acts to reduce the great number of sites where intelligent life might arise to the tiny number of intelligent species with advanced civilizations actually observed (currently just one: human). This probability threshold, which could lie behind us (in our past) or in front of us (in our future), might work as a barrier to the evolution of intelligent life, or as a high probability of self-destruction. The main conclusion of this argument is that the easier it was for life to evolve to our stage, the bleaker our future chances probably are.
'''
[[dependencies.kellomod]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.kellomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
